### ISSUE TITLE
key generate prb

### ISSUE THREAD

**Issue by tncyysl** [ttlequals0/autovpn#15]
i got the some errors,

```
Generating new keypair for eu-central-1.
Traceback (most recent call last):
  File "./scripts/keygen.py", line 11, in <module>
    conn_region = boto.ec2.connect_to_region(region)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/ec2/__init__.py", line 66, in connect_to_region
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/regioninfo.py", line 187, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/ec2/connection.py", line 103, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/auth.py", line 997, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
Key already exists in AWS

```
what could it be meaning ?

**Comment by ttlequals0** [comment]
It looks like you have a key already in that region. Try autovpn -D -r eu-central-1 -k eu-central-1_vpnkey

**Comment by tncyysl** [comment]
the error continues..

```
./autovpn -D -r eu-central-1 -k eu-central-1_vpnkey
WARNING: Keypair eu-central-1_vpnkey in eu-central-1 will be deleted. This is not reversible
Are you sure you want to continue? y/n :yTraceback (most recent call last):
  File "./scripts/delete_key.py", line 10, in <module>
    conn_region = boto.ec2.connect_to_region(region)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/ec2/__init__.py", line 66, in connect_to_region
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/regioninfo.py", line 187, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/ec2/connection.py", line 103, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python2.7/site-packages/boto-2.45.0-py2.7.egg/boto/auth.py", line 997, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials

Failed to delete keypair

```

**Comment by ttlequals0** [comment]
Did you look at the aws management console for that region. Dose a key actually exists.

**Comment by tncyysl** [comment]
i checked it before commenting but it isn't seem still.

**Comment by ttlequals0** [comment]
Taking a closer look it looks like your either missing credentials file or there is a typo in file. Error message shows "Check your credentials"
