### ISSUE TITLE
Does not work in eu-west-2

### ISSUE THREAD

**Issue by ciudilo** [ttlequals0/autovpn#20]
Getting the following error when trying to  create an endpoint in eu-west-2 region.

```
Creating ec2 instance in eu-west-2. This can take some time...
Traceback (most recent call last):
  File "./scripts/create_ec2.py", line 66, in <module>
    auto_vpn()
  File "./scripts/create_ec2.py", line 31, in auto_vpn
    except ec2.ResponseError, e:
AttributeError: 'NoneType' object has no attribute 'ResponseError'
Error code 4
```

**Comment by ttlequals0** [comment]
What command did you use?

**Comment by ciudilo** [comment]
Here is the command I used:

` ./autovpn -C -r eu-west-2 -k KeyName`

**Comment by ttlequals0** [comment]
please update boto and awscli

**Comment by ciudilo** [comment]
My bad, upgrading awscli and boto solved the problem.
