### ISSUE TITLE
Error code 4

### ISSUE THREAD

**Issue by artjia** [ttlequals0/autovpn#21]
Hi, I keep getting this error

```
$ ./autovpn -G -r ap-southeast-2
Generating new keypair for ap-southeast-2.
ap-southeast-2_vpnkey has been created
Use ap-southeast-2_vpnkey as keyname to create endpoint.

$ ./autovpn -C -r ap-southeast-2 -k ap-southeast-2_vpnkey.pem
Creating ec2 instance in ap-southeast-2. This can take some time...
Traceback (most recent call last):
  File "./scripts/create_ec2.py", line 66, in <module>
    auto_vpn()
  File "./scripts/create_ec2.py", line 51, in auto_vpn
    user_data=user_data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/boto/ec2/connection.py", line 977, in run_instances
    verb='POST')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidKeyPair.NotFound</Code><Message>The key pair 'ap-southeast-2_vpnkey.pem' does not exist</Message></Error></Errors><RequestID>af50df26-113d-40c8-921b-7a51c54feae6</RequestID></Response>
Error code 4
DESCRIPTION:
         autovpn - AWS OpenVPN Deployment Tool.
	 Project found at https://github.com/ttlequals0/autovpn
USAGE:
  ACTION	 [OPTIONS]
  -C	 Create VPN endpoint.
  -D	 Delete keypair from region.
  -G	 Generate new keypair.
  -S	 Get all running instances in a given region.
  -T	 Terminate a OpenVPN endpoint.
  -a	 Specify a custom ami.*
  -h	 Displays this message.
  -i	 AWS Instance type (Optional, Default is t2.micro)
	 t2.nano t2.micro t2.small t2.medium t2.large **
  -k	 Specify the name of AWS keypair.
  -m	 Allow multiple connections to same endpoint.
  -r	 Specify AWS Region.
	 us-east-1 us-east-2 us-west-1 us-west-2 eu-west-1 eu-west-2
	 eu-central-1 ap-southeast-1 ap-northeast-1 ap-northeast-2
	 sa-east-1 ap-southeast-2 ap-south-1 ca-central-1.
  -u	 Specify custom ssh user.***
  -y	 Skip confirmations
  -z	 Specify instance id.
EXAMPLES:
  Create OpenVPN endpoint:
	autovpn -C -r us-east-1 -k macbook
  Generate keypar in a region.
	autovpn -G -r us-east-1
  Get running instances
	autovpn -S -r us-west-1
  Terminate OpenVPN endpoint
	autovpn -T -r us-west-1 -z i-b933e00c
  Using custom options
  	autovpn -C -r us-east-1 -k macbook -a ami-fce3c696 -u ec2_user -i m3.medium
NOTES:
 * - Customs ami may be needed if changing instance type.
 ** - In reality any  instance size can be given but the t2.micro
 is more than enough.
 *** - Custom user might be need if using a custom ami.
```

I dont understand why it keep saying key-pair not exist. any idea guys?

**Comment by rpbaptist** [comment]
If you found the solution could you share it?

**Comment by ttlequals0** [comment]
If I recall the issue is the .pem isn't needed when specifying a key.
