### ISSUE TITLE
Error code 4

### ISSUE THREAD

**Issue by anthony-cervantes** [ttlequals0/autovpn#31]
Getting the following error tried with nano and small instance types as well

```bash
➜  autovpn git:(master) ./autovpn -C -r us-east-1 -k us-east-1_vpnkey.pem
Creating ec2 instance in us-east-1. This can take some time...
Traceback (most recent call last):
  File "./scripts/create_ec2.py", line 69, in <module>
    auto_vpn()
  File "./scripts/create_ec2.py", line 54, in auto_vpn
    user_data=user_data)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 977, in run_instances
    verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>VPCResourceNotSpecified</Code><Message>The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.</Message></Error></Errors><RequestID>112fa4aa-383c-4511-8120-6117b6574974</RequestID></Response>
Error code 4
```

**Comment by ttlequals0** [comment]
Remove the .pem from key name.

**Comment by anthony-cervantes** [comment]
still the same issue

**Comment by ttlequals0** [comment]
Do you have proper permissions to create instances and VPCs?
