### ISSUE TITLE
How to specify VPC id?

### ISSUE THREAD

**Issue by oliverlundquist** [ttlequals0/autovpn#38]
Thanks for a great repo, I'm trying to get this to work but can't find a way to boot a t2.micro instance since it says that it has to be inside a VPC? How can we specify a VPC id?

```
autovpn_1  | Creating ec2 instance in us-east-1. This can take some time...
autovpn_1  | Traceback (most recent call last):
autovpn_1  |   File "./scripts/create_ec2.py", line 69, in <module>
autovpn_1  |     auto_vpn()
autovpn_1  |   File "./scripts/create_ec2.py", line 54, in auto_vpn
autovpn_1  |     user_data=user_data)
autovpn_1  |   File "/usr/local/lib/python3.6/site-packages/boto/ec2/connection.py", line 977, in run_instances
autovpn_1  |     verb='POST')
autovpn_1  |   File "/usr/local/lib/python3.6/site-packages/boto/connection.py", line 1208, in get_object
autovpn_1  |     raise self.ResponseError(response.status, response.reason, body)
autovpn_1  | boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
autovpn_1  | <?xml version="1.0" encoding="UTF-8"?>
autovpn_1  | <Response><Errors><Error><Code>VPCResourceNotSpecified</Code><Message>The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.</Message></Error></Errors><RequestID>3e3576b0-8b22-4239-9e4a-27b2bd11e15d</RequestID></Response>
autovpn_1  | Error code 4
```

**Comment by ttlequals0** [comment]
The script assumes you have a default VPC in the region you are deploying
to. Check the AWS console to see if you have a Default VPC.
