### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by ngx3** [ttlequals0/autovpn#49]
Hi, I can't seem to get this working

*Installed paramiko
*Installed boto
*Installed openvpn client
*Installed python-pip

> mkvirtualenv -p python2 env/
> source env/bin/activate
Spits back command not found and bash: env/bin/activate: No such file or directory

I tried ./autovpn -G -r us-east-1  &  ./autovpn -G -r us-west-1 with error:

> Generating new keypair for us-east-1.
> Traceback (most recent call last):
>   File "./scripts/keygen.py", line 3, in <module>
>     import boto
> ImportError: No module named boto
> Key already exists in AWS

I type ./autovpn -C -r us-east-1 -k us-east-1_vpnkey, man page comes up, nothing else. No matter what I try.

Edit**

New error

`Generating` new keypair for us-east-1.
Traceback (most recent call last):
  File "./scripts/keygen.py", line 11, in <module>
    conn_region = boto.ec2.connect_to_region(region)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/ec2/__init__.py", line 66, in connect_to_region
    connection_cls=EC2Connection, **kw_params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/regioninfo.py", line 220, in connect
    return region.connect(**kw_params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/regioninfo.py", line 290, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/ec2/connection.py", line 103, in __init__
    profile_name=profile_name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
Key already exists in AWS

**Comment by ttlequals0** [comment]
try using virtualenvwrapper.
https://virtualenvwrapper.readthedocs.io/en/latest/

`pip install virtualenvwrapper
export WORKON_HOME=~/Envs
mkdir -p $WORKON_HOME
source /usr/local/bin/virtualenvwrapper.sh
mkvirtualenv autovpn`

inside the virtual env run:
`pip install boto`
